Implement Statistics Page
OnlineTrainingPlatform/UI pull request #23
Opened 2022-11-07 08:56 UTC by JakobFaarGreg

## Description
Implement the MVP of the statistics page

### Type of change
- [ ] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
Monkey test

### Checklist:

- [ ] You have added a clear title and description for the PR
- [ ] The CI pass
- [ ] There are no merge conflicts
- [ ] The code satisfies the [code standards](https://docs.google.com/document/d/1R9n9MeuRwz3WSrnWZUjrbmGeosTlu1Xz8f5F7gu2AJE/edit#heading=h.e9xl4xfoldow) 
- [ ] I have added docstrings for my code, where needed
- [ ] Code implements intended functionality
- [ ] All relevant tests pass (Black, White, Integration, Monkey, etc.)

2022-11-08 08:57 UTC, AlexanderHHansen commented on src/Pages/ExercisePage.tsx
>  const EXERCISE_PAGE_BREADCRUMB = 'Exercise Page';
breadcrumb?

2022-11-08 09:01 UTC, AlexanderHHansen commented on src/Pages/StatisticsPage.tsx
>      <>
Et html element uden navn?

2022-11-08 09:01 UTC, AlexanderHHansen commented on src/Pages/StatisticsPage.tsx
>          breadcrumb={STATISTICS_PAGE_BREADCRUMB}
hvad er breadcrumb?

2022-11-08 09:15 UTC, AlexanderHHansen commented on src/Util/createQueryStatisticsListElements.tsx
> +export const createQueryStatisticsListElements = (queries: any[]) => {
Hvorfor bruge any? Kender vi ikke typen?

2022-11-08 09:16 UTC, AlexanderHHansen commented on src/Util/createQueryStatisticsListElements.tsx
> +  if (!queries) {
Går ud fra det bruges til at tjekke om listen er tom. Hvis det er konvention så ok, men ellers syntes jeg noget i stilen af: 
array.length == 0 
er mere læsbart. Det bliver vidst også gjort andre steder

2022-11-08 09:17 UTC, AlexanderHHansen commented on src/Util/createQueryStatisticsListElements.tsx
> +  return queries.map((elem: any) => {
helst ikke brug any

2022-11-08 09:18 UTC, AlexanderHHansen commented on src/Util/createQueryListElements.tsx
> +export const createQueryListElements = (queries: any[]) => {
Brug den korrekte type

2022-11-08 09:18 UTC, AlexanderHHansen commented on src/Util/createQueryListElements.tsx
> +  return queries.map((elem: Query) => {
Så vi kender godt typen. Brug den på linje 4.

2022-11-08 09:20 UTC, AlexanderHHansen commented on src/Pages/StatisticsPage.tsx
> +  const statisticsID = 'Jakob';
Jakob

2022-11-08 09:21 UTC, AlexanderHHansen commented on src/Components/StatisticsPage/QueryStatisticsListElement.tsx
> +    <>
Et html element uden navn?

2022-11-08 09:23 UTC, AlexanderHHansen requested changes
Mest bare nogle nitpicky ting

2022-11-08 13:17 UTC, frejaz commented on src/Util/createQueryListElements.tsx
> +        result={!!elem.result ? elem.result : false}
Fyr lige en kommentar med hvad der sker

2022-11-08 13:20 UTC, frejaz commented on src/Util/createQueryListElements.tsx
> +export const createQueryListElements = (queries: any[]) => {
Mangler docstring

2022-11-08 13:23 UTC, frejaz commented on src/Components/ExercisePage/Queries.tsx
>  export const Queries = () => {
docstrings

2022-11-08 13:24 UTC, frejaz commented on src/Components/ExercisePage/QueryListElement.tsx
>  export const QueryListElement = ({ query, result }: Props) => {
docstrings

2022-11-08 13:25 UTC, frejaz commented on src/Components/LandingPage/ExerciseListElement.tsx
>  export const ExerciseListElement = ({ title, description }: Props) => {
docstrings

2022-11-08 13:27 UTC, frejaz commented on src/Components/StatisticsPage/QueryStatisticsListElement.tsx
> +export const QueryStatisticsListElement = ({
docstrings

2022-11-08 13:28 UTC, frejaz commented on src/Hooks/getQueriesByID.tsx
> +export const useGetQueriesByID = (id: string) => {
docstrings

2022-11-08 13:30 UTC, frejaz commented on src/Pages/StatisticsPage.tsx
> +  const statisticsID = 'Jakob';
Ingen shitposts i koden!

2022-11-08 13:32 UTC, frejaz requested changes
Lav nogle docstrings

2022-11-10 07:54 UTC, JakobFaarGreg commented on src/Pages/ExercisePage.tsx
>  const EXERCISE_PAGE_BREADCRUMB = 'Exercise Page';
Jeg bruger begrebet breadcrumb fordi det skal være et navigationselement. https://en.wikipedia.org/wiki/Breadcrumb_navigation

2022-11-10 07:54 UTC, JakobFaarGreg commented on src/Pages/StatisticsPage.tsx
>      <>
Det hedder et fragment. Man bruger det hvis man ønsker at returnere flere end ét html-element uden at man går op i hvad det wrappes i.

2022-11-10 09:41 UTC, frejaz approved these changes
Love me some docstrings

2022-11-10 09:41 UTC, AlexanderHHansen approved these changes
All looks good now

2022-11-10 09:41 UTC, merged