Feat/connect UI to api
OnlineTrainingPlatform/UI pull request #24
Opened 2022-11-21 12:00 UTC by JakobFaarGreg

## Description
Added UI integration with deployed APIs.
Landing page fetches exercises from Exercises microservice.
Exercise page fetches an individual exercise from the Exercises microservice.
Verify queries, on Exercise page, runs a verification on the queries for this exercise against the uploaded model.

### Type of change
- [ ] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
Monkey tests

### Checklist:

- [ ] You have added a clear title and description for the PR
- [ ] The CI pass
- [ ] There are no merge conflicts
- [ ] The code satisfies the [code standards](https://docs.google.com/document/d/1R9n9MeuRwz3WSrnWZUjrbmGeosTlu1Xz8f5F7gu2AJE/edit#heading=h.e9xl4xfoldow) 
- [ ] I have added docstrings for my code, where needed
- [ ] Code implements intended functionality
- [ ] All relevant tests pass (Black, White, Integration, Monkey, etc.)

2022-11-21 14:02 UTC, fatimaosman99 reviewed
Look fine. Few comments.

2022-11-24 07:57 UTC, frejaz commented on src/Pages/ExercisePage.tsx
> +  const handleVerifyClick = async () => {
docstrings?

2022-11-24 07:57 UTC, frejaz commented on src/Pages/ExercisePage.tsx
> +  useEffect(() => {
docstrings?

2022-11-24 07:59 UTC, frejaz requested changes
Maybe add some comments

2022-11-24 08:03 UTC, fatimaosman99 requested changes
Looks good. Have two comments.

2022-11-25 11:02 UTC, fatimaosman99 approved these changes

2022-11-25 11:06 UTC, frejaz approved these changes
yes

2022-11-25 11:06 UTC, merged